# Generated by Django 4.0.2 on 2024-01-03 05:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texeclientapp', '0002_alter_registration_joindate'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='stage',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='joindate',
            field=models.DateField(default=datetime.date(2024, 1, 3), null=True),
        ),
    ]
