# Generated by Django 4.0.2 on 2024-01-06 12:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texeclientapp', '0004_orders_delivery_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='joindate',
            field=models.DateField(default=datetime.date(2024, 1, 6), null=True),
        ),
    ]
