# Generated by Django 4.0.2 on 2024-01-02 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texecrmapp', '0002_alter_complaint_service_date_register_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders_crm',
            name='stage',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='orders_crm',
            name='status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
