# Generated by Django 4.0.2 on 2024-01-03 05:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texecrmapp', '0003_orders_crm_stage_alter_orders_crm_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint_service',
            name='date_register',
            field=models.DateField(default=datetime.date(2024, 1, 3)),
        ),
        migrations.AlterField(
            model_name='users',
            name='joindate',
            field=models.DateField(default=datetime.date(2024, 1, 3), null=True),
        ),
    ]
