# Generated by Django 4.0.2 on 2024-01-02 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('texeworkapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='complaint_service',
        ),
    ]
